import json
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from typing import Dict, List

class MedicalReportGenerator:
    """
    NLP module for generating medical reports from chest X-ray findings
    """
    
    def __init__(self, model_name="google/flan-t5-base"):
        """
        Initialize the medical report generator
        
        Args:
            model_name (str): Name of the pre-trained language model
        """
        # Initialize tokenizer and model
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
        
        # Define report templates
        # Define report templates
        self.report_template = """
        DIAGNOSTIC RADIOLOGY REPORT
        ===========================
        
        PATIENT INFORMATION
        -------------------
        Examination Date: {date}
        Modality: Chest X-Ray (PA/Lateral)
        
        CLINICAL INDICATION
        -------------------
        {clinical_indication}
        
        FINDINGS
        --------
        {findings}
        
        IMPRESSION
        ----------
        {impression}
        
        RECOMMENDATIONS
        ---------------
        {recommendations}
        
        -----------------------------------------------------------------------
        Electronically signed by AI Assistant.
        This report was generated by an Artificial Intelligence system.
        Please consult with a board-certified radiologist for final verification.
        """
        
        # Define pathology descriptions
        # Define pathology descriptions
        self.pathology_descriptions = {
            'Pneumonia': 'Infection that inflames air sacs in one or both lungs, which may fill with fluid.',
            'Tuberculosis': 'Infectious disease generally affecting the lungs, caused by Mycobacterium tuberculosis.',
            'Pleural Effusion': 'Buildup of excess fluid between the layers of the pleura outside the lungs.',
            'Pneumothorax': 'Presence of air or gas in the cavity between the lungs and the chest wall, causing collapse.',
            'Congestive Heart Failure': 'Chronic condition where the heart doesn\'t pump blood as well as it should, often leading to fluid retention.'
        }
        
    def format_findings(self, predictions: Dict[str, Dict]) -> str:
        """
        Format the CV predictions into a readable findings section
        
        Args:
            predictions (dict): Dictionary of pathology predictions
            
        Returns:
            str: Formatted findings text
        """
        findings = []
        high_confidence_findings = []
        medium_confidence_findings = []
        low_confidence_findings = []
        
        # Categorize findings by confidence
        for pathology, data in predictions.items():
            probability = data['probability']
            confidence = data['confidence']
            description = self.pathology_descriptions.get(pathology, 'No description available')
            
            finding_text = f"- {pathology}: {description} (Probability: {probability:.2f})"
            
            if confidence == 'High':
                high_confidence_findings.append(finding_text)
            elif confidence == 'Medium':
                medium_confidence_findings.append(finding_text)
            else:
                low_confidence_findings.append(finding_text)
        
        # Build findings section
        if high_confidence_findings:
            findings.append("High Confidence Findings:")
            findings.extend(high_confidence_findings)
            findings.append("")
            
        if medium_confidence_findings:
            findings.append("Medium Confidence Findings:")
            findings.extend(medium_confidence_findings)
            findings.append("")
            
        if low_confidence_findings:
            findings.append("Low Confidence Findings:")
            findings.extend(low_confidence_findings)
            
        if not findings:
            findings.append("No significant abnormalities detected.")
            
        return "\n".join(findings)
    
    def generate_impression(self, predictions: Dict[str, Dict]) -> str:
        """
        Generate an impression section based on findings
        
        Args:
            predictions (dict): Dictionary of pathology predictions
            
        Returns:
            str: Impression text
        """
        # Count findings by confidence level
        high_count = sum(1 for data in predictions.values() if data['confidence'] == 'High')
        medium_count = sum(1 for data in predictions.values() if data['confidence'] == 'Medium')
        low_count = sum(1 for data in predictions.values() if data['confidence'] == 'Low')
        
        # Generate impression based on findings
        if high_count > 0:
            impression = f"Significant abnormalities detected with {high_count} high-confidence findings. "
            if medium_count > 0:
                impression += f"Additionally, {medium_count} medium-confidence findings require consideration. "
            if low_count > 0:
                impression += f"{low_count} low-confidence findings noted but may represent normal variants."
        elif medium_count > 0:
            impression = f"Several medium-confidence findings detected ({medium_count} total). "
            impression += "These may represent early or subtle abnormalities requiring clinical correlation. "
            if low_count > 0:
                impression += f"{low_count} low-confidence findings also noted."
        elif low_count > 0:
            impression = f"Few low-confidence findings detected ({low_count} total). "
            impression += "These likely represent normal variants but should be considered in clinical context."
        else:
            impression = "No significant abnormalities detected. Chest X-ray appears normal within limits of this analysis."
            
        return impression
    
    def generate_recommendations(self, predictions: Dict[str, Dict]) -> str:
        """
        Generate recommendations based on findings
        
        Args:
            predictions (dict): Dictionary of pathology predictions
            
        Returns:
            str: Recommendations text
        """
        # Count findings by confidence level
        high_count = sum(1 for data in predictions.values() if data['confidence'] == 'High')
        medium_count = sum(1 for data in predictions.values() if data['confidence'] == 'Medium')
        
        # Generate recommendations based on findings
        if high_count > 0:
            recommendations = "1. Clinical correlation strongly recommended.\n"
            recommendations += "2. Consider additional imaging (CT chest) for further characterization.\n"
            recommendations += "3. Consult with radiologist for detailed interpretation.\n"
            recommendations += "4. Follow-up imaging may be indicated depending on clinical course."
        elif medium_count > 0:
            recommendations = "1. Clinical correlation recommended.\n"
            recommendations += "2. Consider follow-up imaging if clinically indicated.\n"
            recommendations += "3. Radiologist consultation may be helpful for confirmation.\n"
            recommendations += "4. Monitor for any changes in clinical symptoms."
        else:
            recommendations = "1. No immediate follow-up imaging required based on this analysis.\n"
            recommendations += "2. Routine clinical care as appropriate.\n"
            recommendations += "3. Consider repeat imaging only if clinically indicated."
            
        return recommendations
    
    def generate_report(self, predictions: Dict[str, Dict], clinical_indication: str = "Routine examination", 
                       date: str = "Today") -> str:
        """
        Generate a complete medical report from CV predictions
        
        Args:
            predictions (dict): Dictionary of pathology predictions
            clinical_indication (str): Reason for the examination
            date (str): Date of examination
            
        Returns:
            str: Complete medical report
        """
        # Format findings
        findings = self.format_findings(predictions)
        
        # Generate impression
        impression = self.generate_impression(predictions)
        
        # Generate recommendations
        recommendations = self.generate_recommendations(predictions)
        
        # Fill template
        report = self.report_template.format(
            date=date,
            clinical_indication=clinical_indication,
            findings=findings,
            impression=impression,
            recommendations=recommendations
        )
        
        return report
    
    def answer_question(self, question: str, predictions: Dict[str, Dict]) -> str:
        """
        Answer a clinical question about the findings
        
        Args:
            question (str): Clinical question
            predictions (dict): Dictionary of pathology predictions
            
        Returns:
            str: Answer to the question
        """
        # Prepare context from predictions
        context_items = []
        for pathology, data in predictions.items():
            prob = data['probability']
            confidence = data['confidence']
            desc = self.pathology_descriptions.get(pathology, '')
            
            # Include all findings but emphasize high probability ones
            if prob > 0.05:
                context_items.append(f"- {pathology}: {confidence} confidence (Probability: {prob:.2f}). {desc}")
        
        context = "\n".join(context_items)
        
        # Create a better prompt for the model
        prompt = f"""You are an expert medical AI assistant helping a doctor. 
Based on the following Chest X-ray analysis findings, answer the user's question clearly and professionally.
Do not just list probabilities unless asked. Explain the medical context if relevant.

FINDINGS:
{context}

USER QUESTION: {question}

ANSWER:"""
        
        # Tokenize and generate response
        inputs = self.tokenizer.encode(prompt, return_tensors="pt", max_length=1024, truncation=True)
        
        with torch.no_grad():
            outputs = self.model.generate(
                inputs, 
                max_length=300, 
                num_beams=5, 
                no_repeat_ngram_size=2,
                early_stopping=True,
                temperature=0.7
            )
            
        answer = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        return answer

# Example usage
if __name__ == "__main__":
    # Initialize report generator
    report_gen = MedicalReportGenerator()
    
    # Example predictions (in practice, these would come from the CV model)
    example_predictions = {
        'Pneumonia': {'probability': 0.85, 'confidence': 'High'},
        'Effusion': {'probability': 0.62, 'confidence': 'Medium'},
        'Atelectasis': {'probability': 0.45, 'confidence': 'Medium'},
        'Cardiomegaly': {'probability': 0.25, 'confidence': 'Low'}
    }
    
    # Generate report
    report = report_gen.generate_report(
        predictions=example_predictions,
        clinical_indication="Fever and cough for 3 days",
        date="2023-06-15"
    )
    
    print("Generated Medical Report:")
    print("=" * 50)
    print(report)
    
    # Example question answering
    question = "What does the presence of pneumonia indicate?"
    answer = report_gen.answer_question(question, example_predictions)
    print("\nQuestion:", question)
    print("Answer:", answer)